name: Azure Login Check

on:
  push:
    branches: [main]

jobs:
  azure-login:
    runs-on: ubuntu-latest

    steps :
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: false
          environment: "AzureCloud"
          allow-no-subscriptions: false
          audience: "api://AzureADTokenExchange"
          auth-type: "SERVICE_PRINCIPAL"


    - name: Show success message
      run: echo "Azure login successful 🎉"
